<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search users
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["users/new", "Create users"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "users/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldUserid" class="col-sm-2 control-label">UserID</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("userID", "type" => "number", "class" => "form-control", "id" => "fieldUserid")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(array("Name", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldName")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEmail" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
        <?php echo $this->tag->selectStatic(array("Email", array(), "class" => "form-control", "id" => "fieldEmail")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPassword" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("Password", "size" => 30, "class" => "form-control", "id" => "fieldPassword")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldOrders" class="col-sm-2 control-label">Orders</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("Orders", "type" => "number", "class" => "form-control", "id" => "fieldOrders")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
